remote_theme: "mmistakes/minimal-mistakes@4.20.1"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      layout: single
      share: true
      sidebar:
        nav: "sidebar_elements"
      header:
        overlay_image: /assets/images/jcobridge.png
        overlay_filter: 0.5
        actions:
          - label: "Nuget"
            url: "https://www.nuget.org/packages/JCOBridge/"
          - label: "Nuget Templates"
            url: "https://www.nuget.org/packages/JCOBridge.Examples.Templates/"
          - label: "Download"
            url: "https://www.jcobridge.com/wpdownloads/"